function doodle(){(function(){window.google=window.google||{};window.google.ml=function(){};var e=function(a,d,c){a=a.split(".");c=c||window;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var b;a.length&&(b=a.shift());)a.length||void 0===d?c=c[b]?c[b]:c[b]={}:c[b]=d},N=function(a,d,c){return a.call.apply(a.bind,arguments)},O=function(a,d,c){if(!a)throw Error();if(2<arguments.length){var b=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);
Array.prototype.unshift.apply(c,b);return a.apply(d,c)}}return function(){return a.apply(d,arguments)}},p=function(a,d,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?N:O;e("google.bindFn",p,void 0);return p.apply(null,arguments)};google.exportSymbol=function(a,d,c){e(a,d,c)};google.exportProperty=function(a,d,c){a[d]=c};e("google.bindFn",p,void 0);e("google.partial",function(a,d){var c=Array.prototype.slice.call(arguments,1);return function(){var d=Array.prototype.slice.call(arguments);
d.unshift.apply(d,c);return a.apply(this,d)}},void 0);var g={k:!1,z:!1,D:!1,opera:!1},f={k:!1,w:!1,c:!1,A:!1,B:!1,C:!1,v:!1,s:!1,p:!1,opera:!1},t="",l="",A=function(a){for(var d in g)g[d]=!1;for(var c in f)f[c]=!1;d=c=null;window.opera?(g.opera=!0,f.opera=!0,c=d=/Opera[\/\s](\S+)/):0<=a.indexOf("MSIE")?(g.k=!0,f.k=!0,c=d=/MSIE\s+([^\);]+)(\)|;)/):0<=a.indexOf("WebKit")?(g.D=!0,c=/Version\/(\S+)/,0<=a.indexOf("Chrome")?(f.v=!0,d=/Chrome\/(\S+)/):0<=a.indexOf("Android")&&0>a.indexOf("Mobile")?(f.s=
!0,d=/Version\/(\S+)/):0<=a.indexOf("Android")&&0<=a.indexOf("Mobile")?(f.p=!0,d=c):0<=a.indexOf("Safari")&&(f.c=!0,d=c),0<=a.indexOf("iPad")?(f.A=!0,f.c)||(f.c=!0,d=c):0<=a.indexOf("iPhone")?(f.B=!0,f.c)||(f.c=!0,d=c):0<=a.indexOf("iPod")&&(f.C=!0,!f.c)&&(f.c=!0,d=c),c=/WebKit\/(\S+)/):0<=a.indexOf("Gecko")&&(g.z=!0,0<=a.indexOf("Firefox")&&(f.w=!0,d=/Firefox\/(\S+)/),c=/rv:([^\);]+)(\)|;)/);c&&(t=(c=c.exec(a))?c[1]:"");d&&(l=(c=d.exec(a))?c[1]:"",f.k&&(a=document?document.documentMode:void 0)&&
a>parseFloat(l)&&(l=a.toFixed(1).toString()));e("google.browser.engine.IE",g.k,void 0);e("google.browser.engine.GECKO",g.z,void 0);e("google.browser.engine.WEBKIT",g.D,void 0);e("google.browser.engine.OPERA",g.opera,void 0);e("google.browser.engine.version",t,void 0);e("google.browser.product.IE",f.k,void 0);e("google.browser.product.FIREFOX",f.w,void 0);e("google.browser.product.SAFARI",f.c,void 0);e("google.browser.product.IPAD",f.A,void 0);e("google.browser.product.IPHONE",f.B,void 0);e("google.browser.product.IPOD",
f.C,void 0);e("google.browser.product.CHROME",f.v,void 0);e("google.browser.product.ANDROID_TABLET",f.s,void 0);e("google.browser.product.ANDROID_MOBILE",f.p,void 0);e("google.browser.product.OPERA",f.opera,void 0);e("google.browser.product.version",l,void 0)};A(google.ua||window.navigator.userAgent);var u=function(a,d){function c(a,c){return a<c?-1:a>c?1:0}var b=0;a=a.replace(/^\s+|\s+$/g,"").split(".");d=d.replace(/^\s+|\s+$/g,"").split(".");for(var f=Math.max(a.length,d.length),e=0;0==b&&e<f;e++){var g=
a[e]||"",h=d[e]||"",k=/(\d*)(\D*)/g,l=/(\d*)(\D*)/g;do{var m=k.exec(g)||["","",""],n=l.exec(h)||["","",""];if(0==m[0].length&&0==n[0].length)break;b=c(0==m[1].length?0:parseInt(m[1],10),0==n[1].length?0:parseInt(n[1],10))||c(0==m[2].length,0==n[2].length)||c(m[2],n[2])}while(0==b)}return b};e("google.browser.init",A,void 0);e("google.browser.compareVersions",u,void 0);e("google.browser.isEngineVersion",function(a){return 0<=u(t,a)},void 0);e("google.browser.isProductVersion",function(a){return 0<=
u(l,a)},void 0);e("google.listen",function(a,d,c){a.addEventListener?a.addEventListener(d,c,!1):a.attachEvent("on"+d,c)},void 0);e("google.unlisten",function(a,d,c){a.removeEventListener?a.removeEventListener(d,c,!1):a.detachEvent("on"+d,c)},void 0);try{google.doodle||(google.doodle={});var q=200,B=-200,C=-200,v,w,x,D=0,E=0,F=0,G=35,y,z=[],h,k,I=function(){return[window.screenLeft||window.screenX||0,window.screenTop||window.screenY||0,document.body.clientWidth||0]},J=function(a,d,c,b){this.x=this.F=
a;this.y=this.G=d;this.r=this.m=c;this.d=100*(Math.random()-.5);this.g=100*(Math.random()-.5);this.o=3+98*Math.random();this.H=.1+.4*Math.random();this.h=0;this.i=1;this.n=!1;this.a=document.createElement("div");a=this.a.style;a.position="absolute";a.zIndex="-1";b="#"+b;k?(this.a.innerHTML=".",a.color=b,a.cursor="default",a.font="100px Monospace"):(this.a.className="circle",a.backgroundColor=b);h.appendChild(this.a)};J.prototype={remove:function(){this.a&&h.removeChild(this.a);this.a=null},update:function(){this.x+=
this.d;this.y+=this.g;this.d=Math.min(50,Math.max(-50,.92*(this.d+(D+F)/this.m)));this.g=Math.min(50,Math.max(-50,.92*(this.g+E/this.m)));var a=B-this.x,b=C-this.y,c=Math.sqrt(a*a+b*b);c<q?(this.d-=a/c*this.o,this.g-=b/c*this.o,this.h+=.4*(.005-this.h),this.i=Math.max(0,.9*this.i-.01),this.d*=1-this.i,this.g*=1-this.i):(this.h+=.005*(this.H-this.h),this.i=Math.min(1,this.i+.03));a=this.F-this.x;b=this.G-this.y;c=Math.sqrt(a*a+b*b);this.d+=a*this.h;this.g+=b*this.h;this.r=this.m+c/8;this.n=.3>c&&.3>
this.d&&.3>this.g;this.n||(a=this.a.style,k||(a.width=a.height=2*this.r+"px"),a.left=this.x-(k?20:0)+"px",a.top=this.y-(k?60:0)+"px")}};var b=function(a,b,c,e){return new J(a,b,c,e)},P=function(){z=[b(-24,10,17,"3d7b90"),b(10,20,14,"3d7b90"),b(60,20,9,"3d7b90"),b(85,20,5,"3d7b90"),b(100,20,3,"3d7b90"),b(40,20,9,"4976f3"),b(42,39,10,"ef9a1e"),b(44,58,12,"d44d61"),b(46,80,14,"4f7af2"),b(48,109,15,"ed9d33"),b(50,140,17,"d44d61"),b(120,20,9,"4976f3"),b(119,39,10,"ef9a1e"),b(117,58,11,"d44d61"),b(116,
80,13,"4f7af2"),b(110,109,15,"ed9d33"),b(105,140,17,"d44d61"),b(140,27,9.5,"d44d61"),b(155,43,9,"ef9a1e"),b(165,60,8,"d44d61"),b(169,78,6,"4f7af2"),b(195,35,9.5,"d44d61"),b(185,53,9,"ef9a1e"),b(180,70,6,"d44d61"),b(210,20,9,"4976f3"),b(212,39,10,"ef9a1e"),b(214,58,11,"d44d61"),b(216,80,13,"4f7af2"),b(218,109,15,"ed9d33"),b(224,140,17,"d44d61"),b(352,45,7,"4976f3"),b(338,30,9,"ef9a1e"),b(320,18,10,"d44d65"),b(292,18,13,"4f7af2"),b(274,39.5,14,"ed9d33"),b(288,64,14,"4f7af2"),b(313,77,12,"d44d65"),b(336,
85,10,"4f7af2"),b(353,98,8,"ed9d33"),b(360,113,7,"d44d61"),b(360,127,7,"d44d61"),b(353,141,8,"ed9d33"),b(333,146,10,"4f7af2"),b(309,148,12,"d44d65"),b(290,140,10,"4f7af2"),b(278,133,7,"d44d61"),b(276,123,5,"d44d61"),b(270,117,3,"d44d61")];var a=I();v=a[0];w=a[1];x=a[2];K()},K=function(){var a=I(),b=a[0],c=a[1];a=a[2];D=b-v;E=c-w;F=a-x;v=b;w=c;x=a;q=Math.max(0,q-2);b=!0;for(c=0;a=z[c++];)a.update(),b&=a.n;G=b?250:35;y=window.setTimeout(K,G)},L=function(a){q=200;B=a.clientX-h.offsetLeft;C=a.clientY-
h.offsetTop},r=function(a){!google.doodle.dotContainer&&google.dstr&&google.rein&&(google.doodle.dotContainer=!0,google.dstr.push(M),google.rein.push(function(){r(!0)}));k=google.browser.engine.IE&&0<google.browser.compareVersions("9",google.browser.engine.version);google.doodle.cpDestroy=M;google.doodle.cpInit=r;if(h=document.getElementById("loading"))a&&k?location.reload(!1):(h.style.background="none",google.listen(document,"mousemove",L),P())},M=function(){google.unlisten(document,"mousemove",
L);y&&window.clearTimeout(y);if(H)for(var a=0,b;b=H[a++];)b.remove();z=[]};google.lastWindowLeft?google.lastWindowLeft({id:"DOODLE"},r):r()}catch(a){google.ml(a,!1,{_sn:"DOODLE"})}})()};
