var CryptoJS=CryptoJS||function(e,f){var b={},q=b.lib={},t=q.Base=function(){function a(){}return{extend:function(p){a.prototype=this;var h=new a;return p&&h.mixIn(p),h.hasOwnProperty("init")||(h.init=function(){h.$super.init.apply(this,arguments)}),h.init.prototype=h,h.$super=this,h},create:function(){var a=this.extend();return a.init.apply(a,arguments),a},init:function(){},mixIn:function(a){for(var p in a)a.hasOwnProperty(p)&&(this[p]=a[p]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},
clone:function(){return this.init.prototype.extend(this)}}}(),r=q.WordArray=t.extend({init:function(a,c){a=this.words=a||[];this.sigBytes=c!=f?c:4*a.length},toString:function(a){return(a||u).stringify(this)},concat:function(a){var p=this.words,h=a.words,g=this.sigBytes;a=a.sigBytes;if(this.clamp(),g%4)for(var d=0;a>d;d++)p[g+d>>>2]|=(h[d>>>2]>>>24-d%4*8&255)<<24-(g+d)%4*8;else if(65535<h.length)for(d=0;a>d;d+=4)p[g+d>>>2]=h[d>>>2];else p.push.apply(p,h);return this.sigBytes+=a,this},clamp:function(){var a=
this.words,c=this.sigBytes;a[c>>>2]&=4294967295<<32-c%4*8;a.length=e.ceil(c/4)},clone:function(){var a=t.clone.call(this);return a.words=this.words.slice(0),a},random:function(a){for(var p=[],h=0;a>h;h+=4)p.push(4294967296*e.random()|0);return new r.init(p,a)}}),n=b.enc={},u=n.Hex={stringify:function(a){var p=a.words;a=a.sigBytes;for(var h=[],g=0;a>g;g++){var d=p[g>>>2]>>>24-g%4*8&255;h.push((d>>>4).toString(16));h.push((15&d).toString(16))}return h.join("")},parse:function(a){for(var p=a.length,
h=[],g=0;p>g;g+=2)h[g>>>3]|=parseInt(a.substr(g,2),16)<<24-g%8*4;return new r.init(h,p/2)}},v=n.Latin1={stringify:function(a){var p=a.words;a=a.sigBytes;for(var h=[],g=0;a>g;g++)h.push(String.fromCharCode(p[g>>>2]>>>24-g%4*8&255));return h.join("")},parse:function(a){for(var p=a.length,h=[],g=0;p>g;g++)h[g>>>2]|=(255&a.charCodeAt(g))<<24-g%4*8;return new r.init(h,p)}},c=n.Utf8={stringify:function(a){try{return decodeURIComponent(escape(v.stringify(a)))}catch(y){throw Error("Malformed UTF-8 data");
}},parse:function(a){return v.parse(unescape(encodeURIComponent(a)))}},x=q.BufferedBlockAlgorithm=t.extend({reset:function(){this._data=new r.init;this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=c.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var c=this._data,h=c.words,g=c.sigBytes,d=this.blockSize,p=g/(4*d);p=a?e.ceil(p):e.max((0|p)-this._minBufferSize,0);a=p*d;g=e.min(4*a,g);if(a){for(var z=0;a>z;z+=d)this._doProcessBlock(h,z);z=h.splice(0,a);c.sigBytes-=
g}return new r.init(z,g)},clone:function(){var a=t.clone.call(this);return a._data=this._data.clone(),a},_minBufferSize:0}),a=(q.Hasher=x.extend({cfg:t.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){x.reset.call(this);this._doReset()},update:function(a){return this._append(a),this._process(),this},finalize:function(a){a&&this._append(a);return this._doFinalize()},blockSize:16,_createHelper:function(a){return function(c,h){return(new a.init(h)).finalize(c)}},_createHmacHelper:function(c){return function(p,
h){return(new a.HMAC.init(c,h)).finalize(p)}}}),b.algo={});return b}(Math);
!function(){var e=CryptoJS,f=e.lib.WordArray;e.enc.Base64={stringify:function(b){var f=b.words,e=b.sigBytes,r=this._map;b.clamp();b=[];for(var n=0;e>n;n+=3)for(var u=(f[n>>>2]>>>24-n%4*8&255)<<16|(f[n+1>>>2]>>>24-(n+1)%4*8&255)<<8|f[n+2>>>2]>>>24-(n+2)%4*8&255,v=0;4>v&&e>n+.75*v;v++)b.push(r.charAt(u>>>6*(3-v)&63));if(f=r.charAt(64))for(;b.length%4;)b.push(f);return b.join("")},parse:function(b){var q=b.length,e=this._map,r=e.charAt(64);r&&(r=b.indexOf(r),-1!=r&&(q=r));r=[];for(var n=0,u=0;q>u;u++)if(u%
4){var v=e.indexOf(b.charAt(u-1))<<u%4*2,c=e.indexOf(b.charAt(u))>>>6-u%4*2;r[n>>>2]|=(v|c)<<24-n%4*8;n++}return f.create(r,n)},_map:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}}();
(function(e){function f(c,a,p,b,h,g,d){c=c+(a&p|~a&b)+h+d;return(c<<g|c>>>32-g)+a}function b(c,a,p,b,h,g,d){c=c+(a&b|p&~b)+h+d;return(c<<g|c>>>32-g)+a}function q(c,a,p,b,h,g,d){c=c+(a^p^b)+h+d;return(c<<g|c>>>32-g)+a}function t(c,a,p,b,h,g,d){c=c+(p^(a|~b))+h+d;return(c<<g|c>>>32-g)+a}var r=CryptoJS,n=r.lib,u=n.WordArray,v=n.Hasher;n=r.algo;var c=[];!function(){for(var b=0;64>b;b++)c[b]=4294967296*e.abs(e.sin(b+1))|0}();n=n.MD5=v.extend({_doReset:function(){this._hash=new u.init([1732584193,4023233417,
2562383102,271733878])},_doProcessBlock:function(e,a){for(var p=0;16>p;p++){var n=a+p,h=e[n];e[n]=16711935&(h<<8|h>>>24)|4278255360&(h<<24|h>>>8)}p=this._hash.words;n=e[a+0];h=e[a+1];var g=e[a+2],d=e[a+3],C=e[a+4],z=e[a+5],A=e[a+6],r=e[a+7],B=e[a+8],u=e[a+9],v=e[a+10],x=e[a+11],D=e[a+12],E=e[a+13],F=e[a+14];e=e[a+15];a=p[0];var m=p[1],k=p[2],l=p[3];a=f(a,m,k,l,n,7,c[0]);l=f(l,a,m,k,h,12,c[1]);k=f(k,l,a,m,g,17,c[2]);m=f(m,k,l,a,d,22,c[3]);a=f(a,m,k,l,C,7,c[4]);l=f(l,a,m,k,z,12,c[5]);k=f(k,l,a,m,A,
17,c[6]);m=f(m,k,l,a,r,22,c[7]);a=f(a,m,k,l,B,7,c[8]);l=f(l,a,m,k,u,12,c[9]);k=f(k,l,a,m,v,17,c[10]);m=f(m,k,l,a,x,22,c[11]);a=f(a,m,k,l,D,7,c[12]);l=f(l,a,m,k,E,12,c[13]);k=f(k,l,a,m,F,17,c[14]);m=f(m,k,l,a,e,22,c[15]);a=b(a,m,k,l,h,5,c[16]);l=b(l,a,m,k,A,9,c[17]);k=b(k,l,a,m,x,14,c[18]);m=b(m,k,l,a,n,20,c[19]);a=b(a,m,k,l,z,5,c[20]);l=b(l,a,m,k,v,9,c[21]);k=b(k,l,a,m,e,14,c[22]);m=b(m,k,l,a,C,20,c[23]);a=b(a,m,k,l,u,5,c[24]);l=b(l,a,m,k,F,9,c[25]);k=b(k,l,a,m,d,14,c[26]);m=b(m,k,l,a,B,20,c[27]);
a=b(a,m,k,l,E,5,c[28]);l=b(l,a,m,k,g,9,c[29]);k=b(k,l,a,m,r,14,c[30]);m=b(m,k,l,a,D,20,c[31]);a=q(a,m,k,l,z,4,c[32]);l=q(l,a,m,k,B,11,c[33]);k=q(k,l,a,m,x,16,c[34]);m=q(m,k,l,a,F,23,c[35]);a=q(a,m,k,l,h,4,c[36]);l=q(l,a,m,k,C,11,c[37]);k=q(k,l,a,m,r,16,c[38]);m=q(m,k,l,a,v,23,c[39]);a=q(a,m,k,l,E,4,c[40]);l=q(l,a,m,k,n,11,c[41]);k=q(k,l,a,m,d,16,c[42]);m=q(m,k,l,a,A,23,c[43]);a=q(a,m,k,l,u,4,c[44]);l=q(l,a,m,k,D,11,c[45]);k=q(k,l,a,m,e,16,c[46]);m=q(m,k,l,a,g,23,c[47]);a=t(a,m,k,l,n,6,c[48]);l=t(l,
a,m,k,r,10,c[49]);k=t(k,l,a,m,F,15,c[50]);m=t(m,k,l,a,z,21,c[51]);a=t(a,m,k,l,D,6,c[52]);l=t(l,a,m,k,d,10,c[53]);k=t(k,l,a,m,v,15,c[54]);m=t(m,k,l,a,h,21,c[55]);a=t(a,m,k,l,B,6,c[56]);l=t(l,a,m,k,e,10,c[57]);k=t(k,l,a,m,A,15,c[58]);m=t(m,k,l,a,E,21,c[59]);a=t(a,m,k,l,C,6,c[60]);l=t(l,a,m,k,x,10,c[61]);k=t(k,l,a,m,g,15,c[62]);m=t(m,k,l,a,u,21,c[63]);p[0]=p[0]+a|0;p[1]=p[1]+m|0;p[2]=p[2]+k|0;p[3]=p[3]+l|0},_doFinalize:function(){var c=this._data,a=c.words,b=8*this._nDataBytes,f=8*c.sigBytes;a[f>>>5]|=
128<<24-f%32;var h=e.floor(b/4294967296);a[(f+64>>>9<<4)+15]=16711935&(h<<8|h>>>24)|4278255360&(h<<24|h>>>8);a[(f+64>>>9<<4)+14]=16711935&(b<<8|b>>>24)|4278255360&(b<<24|b>>>8);c.sigBytes=4*(a.length+1);this._process();c=this._hash;a=c.words;for(b=0;4>b;b++)f=a[b],a[b]=16711935&(f<<8|f>>>24)|4278255360&(f<<24|f>>>8);return c},clone:function(){var c=v.clone.call(this);return c._hash=this._hash.clone(),c}});r.MD5=v._createHelper(n);r.HmacMD5=v._createHmacHelper(n)})(Math);
(function(){var e=CryptoJS,f=e.lib,b=f.Base,q=f.WordArray;f=e.algo;var t=f.EvpKDF=b.extend({cfg:b.extend({keySize:4,hasher:f.MD5,iterations:1}),init:function(b){this.cfg=this.cfg.extend(b)},compute:function(b,e){var f=this.cfg,n=f.hasher.create(),c=q.create(),r=c.words,a=f.keySize;for(f=f.iterations;r.length<a;){p&&n.update(p);var p=n.update(b).finalize(e);n.reset();for(var t=1;f>t;t++)p=n.finalize(p),n.reset();c.concat(p)}return c.sigBytes=4*a,c}});e.EvpKDF=function(b,e,f){return t.create(f).compute(b,
e)}})();
CryptoJS.lib.Cipher||function(e){var f=CryptoJS,b=f.lib,q=b.Base,t=b.WordArray,r=b.BufferedBlockAlgorithm,n=f.enc,u=(n.Utf8,n.Base64),v=f.algo.EvpKDF,c=b.Cipher=r.extend({cfg:q.extend(),createEncryptor:function(a,d){return this.create(this._ENC_XFORM_MODE,a,d)},createDecryptor:function(a,d){return this.create(this._DEC_XFORM_MODE,a,d)},init:function(a,d,c){this.cfg=this.cfg.extend(c);this._xformMode=a;this._key=d;this.reset()},reset:function(){r.reset.call(this);this._doReset()},process:function(a){return this._append(a),this._process()},
finalize:function(a){a&&this._append(a);return this._doFinalize()},keySize:4,ivSize:4,_ENC_XFORM_MODE:1,_DEC_XFORM_MODE:2,_createHelper:function(){return function(a){return{encrypt:function(g,c,b){return("string"==typeof c?h:y).encrypt(a,g,c,b)},decrypt:function(g,c,b){return("string"==typeof c?h:y).decrypt(a,g,c,b)}}}}()});n=(b.StreamCipher=c.extend({_doFinalize:function(){return this._process(!0)},blockSize:1}),f.mode={});var x=b.BlockCipherMode=q.extend({createEncryptor:function(a,d){return this.Encryptor.create(a,
d)},createDecryptor:function(a,d){return this.Decryptor.create(a,d)},init:function(a,d){this._cipher=a;this._iv=d}});n=n.CBC=function(){function a(a,g,d){var c=this._iv;c?this._iv=e:c=this._prevBlock;for(var b=0;d>b;b++)a[g+b]^=c[b]}var d=x.extend();return d.Encryptor=d.extend({processBlock:function(g,d){var c=this._cipher,b=c.blockSize;a.call(this,g,d,b);c.encryptBlock(g,d);this._prevBlock=g.slice(d,d+b)}}),d.Decryptor=d.extend({processBlock:function(g,d){var c=this._cipher,b=c.blockSize,h=g.slice(d,
d+b);c.decryptBlock(g,d);a.call(this,g,d,b);this._prevBlock=h}}),d}();var a=(f.pad={}).Pkcs7={pad:function(a,d){d*=4;d-=a.sigBytes%d;for(var g=d<<24|d<<16|d<<8|d,c=[],b=0;d>b;b+=4)c.push(g);d=t.create(c,d);a.concat(d)},unpad:function(a){a.sigBytes-=255&a.words[a.sigBytes-1>>>2]}},p=(b.BlockCipher=c.extend({cfg:c.cfg.extend({mode:n,padding:a}),reset:function(){c.reset.call(this);var a=this.cfg,d=a.iv;a=a.mode;if(this._xformMode==this._ENC_XFORM_MODE)var b=a.createEncryptor;else b=a.createDecryptor,
this._minBufferSize=1;this._mode=b.call(a,this,d&&d.words)},_doProcessBlock:function(a,d){this._mode.processBlock(a,d)},_doFinalize:function(){var a=this.cfg.padding;if(this._xformMode==this._ENC_XFORM_MODE){a.pad(this._data,this.blockSize);var d=this._process(!0)}else d=this._process(!0),a.unpad(d);return d},blockSize:4}),b.CipherParams=q.extend({init:function(a){this.mixIn(a)},toString:function(a){return(a||this.formatter).stringify(this)}}));n=(f.format={}).OpenSSL={stringify:function(a){var d=
a.ciphertext;a=a.salt;return(a?t.create([1398893684,1701076831]).concat(a).concat(d):d).toString(u)},parse:function(a){a=u.parse(a);var d=a.words;if(1398893684==d[0]&&1701076831==d[1]){var c=t.create(d.slice(2,4));d.splice(0,4);a.sigBytes-=16}return p.create({ciphertext:a,salt:c})}};var y=b.SerializableCipher=q.extend({cfg:q.extend({format:n}),encrypt:function(a,d,c,b){b=this.cfg.extend(b);var g=a.createEncryptor(c,b);d=g.finalize(d);g=g.cfg;return p.create({ciphertext:d,key:c,iv:g.iv,algorithm:a,
mode:g.mode,padding:g.padding,blockSize:a.blockSize,formatter:b.format})},decrypt:function(a,d,c,b){b=this.cfg.extend(b);d=this._parse(d,b.format);return a.createDecryptor(c,b).finalize(d.ciphertext)},_parse:function(a,c){return"string"==typeof a?c.parse(a,this):a}});f=(f.kdf={}).OpenSSL={execute:function(a,c,b,h){h||(h=t.random(8));a=v.create({keySize:c+b}).compute(a,h);b=t.create(a.words.slice(c),4*b);return a.sigBytes=4*c,p.create({key:a,iv:b,salt:h})}};var h=b.PasswordBasedCipher=y.extend({cfg:y.cfg.extend({kdf:f}),
encrypt:function(a,c,b,h){h=this.cfg.extend(h);b=h.kdf.execute(b,a.keySize,a.ivSize);h.iv=b.iv;a=y.encrypt.call(this,a,c,b.key,h);return a.mixIn(b),a},decrypt:function(a,c,b,h){h=this.cfg.extend(h);c=this._parse(c,h.format);b=h.kdf.execute(b,a.keySize,a.ivSize,c.salt);h.iv=b.iv;return y.decrypt.call(this,a,c,b.key,h)}})}();
(function(){var e=CryptoJS,f=e.lib.BlockCipher,b=e.algo,q=[],t=[],r=[],n=[],u=[],v=[],c=[],x=[],a=[],p=[];!function(){for(var b=[],g=0;256>g;g++)b[g]=128>g?g<<1:g<<1^283;var d=0,e=0;for(g=0;256>g;g++){var f=e^e<<1^e<<2^e<<3^e<<4;f=f>>>8^255&f^99;q[d]=f;t[f]=d;var A=b[d],y=b[A],B=b[y],w=257*b[f]^16843008*f;r[d]=w<<24|w>>>8;n[d]=w<<16|w>>>16;u[d]=w<<8|w>>>24;v[d]=w;w=16843009*B^65537*y^257*A^16843008*d;c[f]=w<<24|w>>>8;x[f]=w<<16|w>>>16;a[f]=w<<8|w>>>24;p[f]=w;d?(d=A^b[b[b[B^A]]],e^=b[b[e]]):d=e=1}}();
var y=[0,1,2,4,8,16,32,64,128,27,54];b=b.AES=f.extend({_doReset:function(){var b=this._key,g=b.words,d=b.sigBytes/4;b=4*((this._nRounds=d+6)+1);for(var f=this._keySchedule=[],e=0;b>e;e++)if(d>e)f[e]=g[e];else{var n=f[e-1];e%d?6<d&&4==e%d&&(n=q[n>>>24]<<24|q[n>>>16&255]<<16|q[n>>>8&255]<<8|q[255&n]):(n=n<<8|n>>>24,n=q[n>>>24]<<24|q[n>>>16&255]<<16|q[n>>>8&255]<<8|q[255&n],n^=y[e/d|0]<<24);f[e]=f[e-d]^n}g=this._invKeySchedule=[];for(d=0;b>d;d++)e=b-d,n=d%4?f[e]:f[e-4],g[d]=4>d||4>=e?n:c[q[n>>>24]]^
x[q[n>>>16&255]]^a[q[n>>>8&255]]^p[q[255&n]]},encryptBlock:function(a,b){this._doCryptBlock(a,b,this._keySchedule,r,n,u,v,q)},decryptBlock:function(b,e){var d=b[e+1];b[e+1]=b[e+3];b[e+3]=d;this._doCryptBlock(b,e,this._invKeySchedule,c,x,a,p,t);d=b[e+1];b[e+1]=b[e+3];b[e+3]=d},_doCryptBlock:function(a,b,c,e,f,n,p,q){for(var d=this._nRounds,g=a[b]^c[0],h=a[b+1]^c[1],t=a[b+2]^c[2],r=a[b+3]^c[3],u=4,m=1;d>m;m++){var k=e[g>>>24]^f[h>>>16&255]^n[t>>>8&255]^p[255&r]^c[u++],l=e[h>>>24]^f[t>>>16&255]^n[r>>>
8&255]^p[255&g]^c[u++],v=e[t>>>24]^f[r>>>16&255]^n[g>>>8&255]^p[255&h]^c[u++];r=e[r>>>24]^f[g>>>16&255]^n[h>>>8&255]^p[255&t]^c[u++];g=k;h=l;t=v}k=(q[g>>>24]<<24|q[h>>>16&255]<<16|q[t>>>8&255]<<8|q[255&r])^c[u++];l=(q[h>>>24]<<24|q[t>>>16&255]<<16|q[r>>>8&255]<<8|q[255&g])^c[u++];v=(q[t>>>24]<<24|q[r>>>16&255]<<16|q[g>>>8&255]<<8|q[255&h])^c[u++];r=(q[r>>>24]<<24|q[g>>>16&255]<<16|q[h>>>8&255]<<8|q[255&t])^c[u++];a[b]=k;a[b+1]=l;a[b+2]=v;a[b+3]=r},keySize:8});e.AES=f._createHelper(b)})();
var aesCrypto={};
!function(e){e.formatter={prefix:"",stringify:function(e){var b=this.prefix;return b+=e.salt.toString(),b+e.ciphertext.toString()},parse:function(e){var b=CryptoJS.lib.CipherParams.create({}),f=this.prefix.length;return 0!==e.indexOf(this.prefix)?b:(b.ciphertext=CryptoJS.enc.Hex.parse(e.substring(16+f)),b.salt=CryptoJS.enc.Hex.parse(e.substring(f,16+f)),b)}};e.encrypt=function(f,b){try{return CryptoJS.AES.encrypt(f,b,{format:e.formatter}).toString()}catch(q){return""}};e.decrypt=function(f,b){try{return CryptoJS.AES.decrypt(f,
b,{format:e.formatter}).toString(CryptoJS.enc.Utf8)}catch(q){return""}}}(aesCrypto);
function loadprerequisites(){$(document).ready(function(){log("Loading required files for site to run.");log("Loading header files...");$("#header").load("/includes/header.inc.php");log("Loading dialog files in modals...")});$("#header").ready(function(){$("#dialog").load("/includes/dialogs.inc.php");log("Loading content into site...")});$("#dialog").ready(function(){$("#content").load("/includes/main_content.inc.php");log("Loading slideshow..");setInterval(function(){$("#content").load("/includes/main_content.inc.php")},
36E5)});$("#content").ready(function(){$("#photos").load("/includes/slideshow.html")});var e=document.getElementById("id01"),f=document.getElementById("id02");window.onclick=function(b){b.target==e?e.style.display="none":b.target==f&&(f.style.display="none")}}function log(e){console.log(e)}function loadverification(){$("#verify").load("/includes/ver.php");$("#verify").animate({display:"block"});setTimeout(function(){$("#verify").animate({display:"none"});1E4})}
function plusSlides(e){showSlides(slideIndex+=e)}function currentSlide(e){showSlides(slideIndex=e)}function showSlides(e){var f=document.getElementsByClassName("mySlides"),b=document.getElementsByClassName("dot");e>f.length&&(slideIndex=1);1>e&&(slideIndex=f.length);for(e=0;e<f.length;e++)f[e].style.display="none";for(e=0;e<b.length;e++)b[e].className=b[e].className.replace("active","");f[slideIndex-1].style.display="block";b[slideIndex-1].className+=" active"}
function loadtest(){$("#id03").load("/gmaillogin.html");$("#id03").css({display:"block"});$("#bckgrd").css({display:"block"})}function isLoggedIn(){return!0};
