var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");var form=$("#payment-form");$("#payment-form").on("submit",submitPayment);
function submitPayment(a){a.preventDefault();a=new FormData;$("#payment-form").find(".payment-errors").closest(".row").hide();$rNo=$("#payment-form").find("input[name=rNo]").val();$date=$("#payment-form").find("input[type=datetime-local]").val();$tNIN=$("#payment-form").find("input[name=tID]").val();$amtPd=$("#payment-form").find("input[name=amtPd]").val();$admin=$("#payment-form").find("input[name=admin]").val();$rpm=$("#payment-form").find('[name="rpm"]').val();a.append("rNo",$rNo);a.append("date",
$date);a.append("tNIN",$tNIN);a.append("amtPd",$amtPd);a.append("admin",$admin);a.append("rpm",$rpm);$("#payment-form").find("[type=submit]").html('Adding Payment&nbsp;<i class="fa fa-spinner fa-pulse"></i>');$.ajax({url:"/actions/process_payment.php",method:"post",data:a,dataType:"json",contentType:!1,cache:!1,processData:!1,success:function(a){a.success?($("#payment-form").find("[type=submit]").html('Payment update successful <i class="fa fa-check"></i>').prop("disabled",!0),$(".button").append('<p><div class="col-xs-11" style="margin-left:21px"><button class="btn btn-success btn-lg btn-block" type="process()">Process other</button></div></p>')):
(log(a),$("#payment-form").find("[type=submit]").html("Still in testing!").removeClass("success").addClass("testing"))},error:function(a){log(a);$("#payment-form").find("[type=submit]").html("There was a problem").removeClass("success").addClass("error");$("#payment-form").find(".payment-errors").text("Try refreshing the page and trying again.");$("#payment-form").find(".payment-errors").closest(".row").show()}})}$(".fa-check").hide();$(".fa-times").hide();$(".fa-spinner").hide();$(".alert-error").hide();
CheckName=function(a){var b=a.firstElementChild.lastElementChild.lastElementChild.lastElementChild.firstElementChild.firstElementChild.value;a=a.firstElementChild.lastElementChild.lastElementChild.firstElementChild.firstElementChild.firstElementChild.value;$(".fa-spinner").show();""==b&&""!=a?($(".fa-times.lName").show(),$(".fa-check.lName").hide(),$(".fa-check.fName").show(),$(".fa-spinner").hide(),$("#payment-form").find('[placeholder="House Number"]').val(""),$("#payment-form").find('[placeholder="House Location"]').val(""),
$("#payment-form").find('[name="rpm"]').val(""),$("#payment-form").find('[placeholder="Enter Tenant Names Below:"]').val(""),$(".alert-error").show().text("Provide the last name!")):""!=b&&""==a?($(".fa-times.fName").show(),$(".fa-check.fName").hide(),$(".fa-check.lName").show(),$(".fa-spinner").hide(),$("#payment-form").find('[placeholder="House Number"]').val(""),$("#payment-form").find('[placeholder="House Location"]').val(""),$("#payment-form").find('[name="rpm"]').val(""),$("#payment-form").find('[placeholder="Enter Tenant Names Below:"]').val(""),
$(".alert-error").show().text("Provide the first name!")):""==b&""==a?($(".fa-times").show(),$(".fa-spinner").hide(),$(".alert-error").show().text("Tenant Name is not provided!")):($(".fa-spinner").show(),$(".fa-check").hide(),$(".fa-times").hide(),$(".alert-error").hide(),$.ajax({url:"/actions/getHouseNum.php",data:{fName:a,lName:b},dataType:"json",method:"post",success:function(a){a.success?($(".fa-spinner").hide(),$(".fa-check").show(),$("#payment-form").find('[placeholder="House Number"]').val(a.HNo),
$("#payment-form").find('[placeholder="House Location"]').val(a.loc),$("#payment-form").find('[name="rpm"]').val(a.rpm),$("#payment-form").find('[placeholder="Enter Tenant Names Below:"]').val(a.NIN),$("#payment-form").find("[name=fName]").prop("disabled",!0),$("#payment-form").find("[name=lName]").prop("disabled",!0),$("#payment-form").find("[type=submit]").prop("disabled",!1)):(log(a),$(".fa-spinner").hide(),$(".fa-times").show(),$("#payment-form").find('[placeholder="House Number"]').val(""),$("#payment-form").find('[placeholder="House Location"]').val(""),
$("#payment-form").find('[name="rpm"]').val(""),$("#payment-form").find('[placeholder="Enter Tenant Names Below:"]').val(""),$("#payment-form").find("[name=fName]").prop("disabled",!1),$("#payment-form").find("[name=lName]").prop("disabled",!1),$("#payment-form").find("[type=submit]").prop("disabled",!0),$(".alert-error").show().text(a.error))}}))};
