var preloadSlides=10,loadingMessageDelay=1500,loadingMessageSpeed=1200,loadingMessageMinOpacity=.4,loadingMessageMaxOpacity=1,captionSpeed=1200,captionOpacity=.5,swipeXThreshold=30,swipeYThreshold=90,leftKeyCode=37,rightKeyCode=39,currentSlideOpacity=1,backgroundSlideOpacity=.5,slideHorizMargin=0,buttonHeight=0,currentSlide=0,totalSlides=0,slides=[],slideWidths=[],slideLoaded=[],slideHeights=[],loading=!0;$(init);
function init(){slideHorizMargin=parseInt($("#gallery img").css("margin-left"));$("#gallery").fadeTo(0,0);$("#gallery").css("top","-999em");buttonHeight=$("#leftBtn").css("height");$("#leftBtn").css("height",0);$("#rightBtn").css("height",0);$("#loading").delay(loadingMessageDelay);fadeInLoadingMessage();$("#gallery img").load(handleSlideLoad);$("#gallery img").each(function(){$(this).hide();$(this).data("slideNum",totalSlides);slides[totalSlides++]=$(this);this.complete&&$(this).trigger("load");
$(this).attr("src",$(this).attr("src"))});$(window).resize(centreCurrentSlide);setButtonStates();$("#caption").html(slides[currentSlide].attr("alt"));$("#caption").css({top:$("#gallery").height()-slides[currentSlide].height()+"px"});$.browser.msie||$("#gallery").swipe({swipeLeft:moveRight,swipeRight:moveLeft,threshold:{x:swipeXThreshold,y:swipeYThreshold}});$(document).keydown(function(a){a.which==leftKeyCode&&moveLeft();a.which==rightKeyCode&&moveRight()});$("#info").bind("touchstart",function(){$(this).toggleClass("hover")})}
function handleSlideLoad(){slideWidths[$(this).data("slideNum")]=$(this).width();$("#gallery").width($("#gallery").width()+$(this).width()+2*slideHorizMargin);slideLoaded[$(this).data("slideNum")]=!0;if(loading){for(var a=0,b=0;b<preloadSlides;b++)slideLoaded[b]&&a++;if(a==preloadSlides||a==totalSlides)$("#loading").clearQueue().stop().fadeTo("slow",0),$("#gallery").css("top",0),$("#gallery").fadeTo("slow",1),$("#leftBtn").css("height",buttonHeight),$("#rightBtn").css("height",buttonHeight),$("#rightBtn").show(),
addSlideHover(),loading=!1,$("#loading").css({display:"none"})}0==$(this).data("slideNum")?(centreCurrentSlide(),$(this).fadeTo("slow",currentSlideOpacity)):$(this).fadeTo("slow",backgroundSlideOpacity)}
function moveLeft(){if(0!=currentSlide&&void 0!=slideWidths[currentSlide-1]){slides[currentSlide].unbind("mouseenter").unbind("mouseleave").unbind("touchstart");$("#caption").stop().clearQueue().hide();var a=slideWidths[currentSlide]/2+2*slideHorizMargin+slideWidths[currentSlide-1]/2;$("#gallery").animate({left:"+="+a});slides[currentSlide].animate({opacity:backgroundSlideOpacity});slides[currentSlide-1].animate({opacity:currentSlideOpacity});currentSlide--;setButtonStates();$("#caption").html(slides[currentSlide].attr("alt"));
addSlideHover()}}
function moveRight(){if(currentSlide!=totalSlides-1&&void 0!=slideWidths[currentSlide+1]){slides[currentSlide].unbind("mouseenter").unbind("mouseleave").unbind("touchstart");$("#caption").stop().clearQueue().hide();var a=slideWidths[currentSlide]/2+2*slideHorizMargin+slideWidths[currentSlide+1]/2;$("#gallery").animate({left:"-="+a});slides[currentSlide].animate({opacity:backgroundSlideOpacity});slides[currentSlide+1].animate({opacity:currentSlideOpacity});currentSlide++;setButtonStates();checkEndSlide();
$("#caption").html(slides[currentSlide].attr("alt"));addSlideHover()}}function centreCurrentSlide(){for(var a=0,b=0;b<currentSlide;b++)a+=slideWidths[b]+2*slideHorizMargin;a=$(window).width()/2-slideWidths[currentSlide]/2-a-slideHorizMargin;$("#gallery").css("left",a-100+"px")}function setButtonStates(){0==currentSlide?$("#leftBtn").hide():$("#leftBtn").show();currentSlide==totalSlides-1?$("#rightBtn").hide():$("#rightBtn").show()}
function getToStart(){for(var a=$count=0;$count!=totalSlides-1;)a+=slideWidths[currentSlide]/2+2*slideHorizMargin+slideWidths[currentSlide-1]/2,$count++;currentSlide=0;$("#gallery").animate({left:"+="+a});slides[currentSlide].animate({opacity:currentSlideOpacity});setButtonStates();centreCurrentSlide()}function checkEndSlide(){currentSlide==totalSlides-1&&setTimeout(getToStart,2E3)}
function addSlideHover(){"ontouchstart"in document.documentElement?slides[currentSlide].bind("touchstart",function(){$("#caption").is(":visible")?$("#caption").stop().clearQueue().fadeOut(captionSpeed):$("#caption").stop().clearQueue().fadeTo(captionSpeed,captionOpacity)}):slides[currentSlide].hover(function(){$("#caption").stop().fadeTo(captionSpeed,captionOpacity)},function(){$("#caption").stop().fadeTo(captionSpeed,0)})}
function fadeInLoadingMessage(){$("#loading").animate({opacity:loadingMessageMaxOpacity},loadingMessageSpeed,"swing",fadeOutLoadingMessage)}function fadeOutLoadingMessage(){$("#loading").animate({opacity:loadingMessageMinOpacity},loadingMessageSpeed,"swing",fadeInLoadingMessage)}function slide(){moveRight();setInterval(moveRight,5E3)}slide();
